# Generated by Django 5.0.1 on 2024-01-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uptaded', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
